
import sys

path = 'adan-pred.js'
with open(path, 'r') as f:
    lines = f.readlines()

new_func = [
    'function updateNeuralFlow(d) {\n',
    '  const wrap = document.getElementById(\'nf-wrap\');\n',
    '  if (!wrap) return;\n',
    '  const isThinking = d.state?.mode === \'thinking\';\n',
    '  const isDone     = d.state?.mode === \'result\';\n',
    '\n',
    '  const prices  = d.state?.prices || {};\n',
    '  const btc = prices[\'BTCUSDT\'];\n',
    '\n',
    '  const frames = [\'⠋\',\'⠙\',\'⠹\',\'⠸\',\'⠼\',\'⠴\',\'⠦\',\'⠧\',\'⠇\',\'⠏\'];\n',
    '  const frame  = frames[Math.floor(Date.now()/150) % frames.length];\n',
    '  const fmt    = (v,dp=2) => v!=null ? v.toFixed(dp) : \'--\';\n',
    '  const chgTxt = (p) => p ? (p.chg>=0?\'+\':\'\')+fmt(p.chg,1)+\'%\' : \'--\';\n',
    '\n',
    '  const C_CARD  = \'#ddd9cc\';\n',
    '  const C_CARD3 = \'#e8e4d8\';\n',
    '  const C_BRD2  = \'#3a3a2a\';\n',
    '  const C_TXT   = \'#1a1a1a\';\n',
    '  const C_DIM   = \'#888878\';\n',
    '  const C_SHD   = \'#1a1a1a\';\n',
    '  const C_CYA   = \'#1a4a8a\';\n',
    '  const C_GRN   = \'#1a5a1a\';\n',
    '  const C_PUR   = \'#5a1a8a\';\n',
    '  const C_YEL   = \'#7a5a10\';\n',
    '  const C_RED   = \'#8a1a1a\';\n',
    '\n',
    '  const lnColor = isThinking ? C_CYA : isDone ? C_GRN : C_BRD2;\n',
    '\n',
    '  const SVG_W = 1000, SVG_H = 450;\n',
    '  const CX = SVG_W / 2, CY = SVG_H / 2;\n',
    '  const ORBIT_R = 150;\n',
    '  const ADAN_R = 40;\n',
    '  const PARENT_R = 30;\n',
    '\n',
    '  const children = d.children || [];\n',
    '  const appleIntel = children.find(c => c.spec === \'apple\');\n',
    '  const snakeIntel = children.find(c => c.spec === \'snake\');\n',
    '  const evaIntel = children.find(c => c.spec === \'eva\');\n',
    '  const atlasIntel = children.find(c => c.spec === \'atlas\');\n',
    '\n',
    '  const parentDefs = [\n',
    '    { id: \'apple\', name: \'APPLE\', icon: \'🍎\', color: C_YEL, angle: -45, intel: appleIntel, l1: appleIntel?.report?.opportunity || \'scanning...\', l2: appleIntel ? \'F&G:\' + (appleIntel.report?.fgValue ?? \'--\') : \'waiting\' },\n',
    '    { id: \'snake\', name: \'SNAKE\', icon: \'🐍\', color: C_GRN, angle: 45, intel: snakeIntel, l1: snakeIntel?.report?.viability || \'scanning...\', l2: snakeIntel ? \'Vol:\' + (snakeIntel.report?.avgVolRatio ?? \'--\') + \'x\' : \'waiting\' },\n',
    '    { id: \'eva\', name: \'EVA\', icon: \'👑\', color: C_RED, angle: 135, intel: evaIntel, l1: evaIntel?.report?.approved ? \'APPROVED\' : (evaIntel ? \'DENIED\' : \'scanning...\'), l2: evaIntel ? \'Risk:\' + (evaIntel.report?.riskLevel || \'--\') : \'waiting\' },\n',
    '    { id: \'atlas\', name: \'ATLAS\', icon: \'👁️‍G\', color: C_PUR, angle: -135, intel: atlasIntel, l1: atlasIntel?.report?.smartMoney || \'scanning...\', l2: atlasIntel ? \'Funding:\' + (atlasIntel.report?.fundingRate || \'--\') : \'waiting\' }\n',
    '  ];\n',
    '\n',
    '  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SVG_W} ${SVG_H}" style="width:100%;height:${SVG_H}px">\n',
    '  <defs>\n',
    '    <marker id="arh-rad" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto">\n',
    '      <path d="M0,0 L0,6 L6,3 z" fill="${lnColor}"/>\n',
    '    </marker>\n',
    '    <radialGradient id="adan-glow" cx="50%" cy="50%" r="50%">\n',
    '      <stop offset="0%" stop-color="${C_PUR}" stop-opacity="0.3"/>\n',
    '      <stop offset="100%" stop-color="${C_PUR}" stop-opacity="0"/>\n',
    '    </radialGradient>\n',
    '  </defs>`;\n',
    '\n',
    '  svg += `<circle cx="${CX}" cy="${CY}" r="${ORBIT_R}" fill="none" stroke="${C_BRD2}" stroke-width="1" stroke-dasharray="4 4" opacity="0.3"/>`;\n',
    '\n',
    '  parentDefs.forEach((p, i) => {\n',
    '    const rad = p.angle * Math.PI / 180;\n',
    '    const px = CX + ORBIT_R * Math.cos(rad);\n',
    '    const py = CY + ORBIT_R * Math.sin(rad);\n',
    '    const distC = Math.sqrt(Math.pow(CX-px,2)+Math.pow(CY-py,2));\n',
    '    const x1 = px + (CX - px) / distC * PARENT_R;\n',
    '    const y1 = py + (CY - py) / distC * PARENT_R;\n',
    '    const x2 = CX - (CX - px) / distC * ADAN_R;\n',
    '    const y2 = CY - (CY - py) / distC * ADAN_R;\n',
    '    const lineOpacity = Math.max(0.3, Math.min(1, (p.intel?.signal?.conf || 30) / 100));\n',
    '    const ptDur = isThinking ? \'0.5s\' : \'1.5s\';\n',
    '\n',
    '    svg += `<path d="M${x1.toFixed(1)},${y1.toFixed(1)} L${x2.toFixed(1)},${y2.toFixed(1)}" stroke="${p.color}" stroke-width="1.5" stroke-dasharray="4 3" fill="none" opacity="${lineOpacity}" marker-end="url(#arh-rad)"/>`;\n',
    '    for(let pt=0; pt<5; pt++) {\n',
    '      svg += `<circle r="2" fill="${p.color}" opacity="${lineOpacity * (1 - pt/10)}">\n',
    '        <animateMotion path="M${x1.toFixed(1)},${y1.toFixed(1)} L${x2.toFixed(1)},${y2.toFixed(1)}" dur="${ptDur}" begin="${pt*0.3}s" repeatCount="indefinite"/>\n',
    '      </circle>`;\n',
    '    }\n',
    '  });\n',
    '\n',
    '  svg += `<circle cx="${CX}" cy="${CY}" r="${ADAN_R + 15}" fill="url(#adan-glow)"/>`;\n',
    '  if (isThinking) {\n',
    '    svg += `<circle cx="${CX}" cy="${CY}" r="${ADAN_R + 8}" fill="none" stroke="${C_CYA}" stroke-width="1.5" opacity=".3" class="nf-pulse"/>`;\n',
    '  }\n',
    '\n',
    '  const adanBorder = isThinking ? C_CYA : isDone ? C_GRN : C_PUR;\n',
    '  svg += `<rect x="${CX-ADAN_R}" y="${CY-ADAN_R}" width="${ADAN_R*2}" height="${ADAN_R*2}" fill="${C_CARD}" stroke="${adanBorder}" stroke-width="2.5" onclick="showAdanDetail()" style="cursor:pointer"/>\n',
    '  <text x="${CX}" y="${CY-12}" text-anchor="middle" font-size="7" font-weight="700" fill="${C_PUR}" font-family="JetBrains Mono,monospace" letter-spacing="1.5">ADAN</text>\n',
    '  <text x="${CX}" y="${CY+4}" text-anchor="middle" font-size="18" fill="${isThinking?C_CYA:C_PUR}" font-family="JetBrains Mono,monospace" font-weight="700">${isThinking?frame:(isDone?\'◉\':\'◈\')}</text>\n',
    '  <text x="${CX}" y="${CY+18}" text-anchor="middle" font-size="8" fill="${C_DIM}" font-family="JetBrains Mono,monospace">${isThinking?\'analyzing\':(isDone?(d.state?.thought?.includes(\'BET\')?\'BET\':\'SKIP\'):\'idle\')}</text>`;\n',
    '\n',
    '  const tSecGlobal = Date.now() / 1000;\n',
    '  parentDefs.forEach((p) => {\n',
    '    const rad = p.angle * Math.PI / 180;\n',
    '    const px = CX + ORBIT_R * Math.cos(rad);\n',
    '    const py = CY + ORBIT_R * Math.sin(rad);\n',
    '    \n',
    '    svg += `<g onclick="showParentDetail(\'${p.id}\')" style="cursor:pointer">\n',
    '      <rect x="${px-PARENT_R}" y="${py-PARENT_R}" width="${PARENT_R*2}" height="${PARENT_R*2}" fill="${C_CARD}" stroke="${p.color}" stroke-width="2"/>\n',
    '      <text x="${px}" y="${py-10}" text-anchor="middle" font-size="6.5" font-weight="700" fill="${p.color}" font-family="JetBrains Mono,monospace">${p.name}</text>\n',
    '      <text x="${px}" y="${py+2}" text-anchor="middle" font-size="12">${p.icon}</text>\n',
    '    </g>`;\n',
    '\n',
    '    const pChildren = children.filter(c => c.status !== \'dead\' && (c.faction?.toLowerCase() === p.id || (c.name && c.name.toLowerCase().startsWith(p.id.charAt(0)))));\n',
    '    const childOrbitR = PARENT_R + 35;\n',
    '    if (pChildren.length > 0) {\n',
    '      svg += `<circle cx="${px}" cy="${py}" r="${childOrbitR}" fill="none" stroke="${p.color}" stroke-width="0.5" stroke-dasharray="2 4" opacity="0.3"/>`;\n',
    '    }\n',
    '\n',
    '    pChildren.forEach((child, ci) => {\n',
    '      const globalIdx = children.indexOf(child);\n',
    '      const startAngle = (tSecGlobal % 16) / 16 * 360 + (ci / pChildren.length) * 360;\n',
    '      svg += `<g transform="translate(${px}, ${py})">\n',
    '        <g>\n',
    '          <animateTransform attributeName="transform" type="rotate" from="${startAngle} 0 0" to="${startAngle + 360} 0 0" dur="16s" repeatCount="indefinite" />\n',
    '          <g transform="translate(${childOrbitR}, 0)">\n',
    '            <g>\n',
    '              <animateTransform attributeName="transform" type="rotate" from="${-startAngle} 0 0" to="${-(startAngle + 360)} 0 0" dur="16s" repeatCount="indefinite" />\n',
    '              <g onclick="showChildDetail(${globalIdx})" style="cursor:pointer;">\n',
    '                <circle cx="0" cy="0" r="8" fill="${C_CARD3}" stroke="${C_CYA}" stroke-width="1.5" />\n',
    '                <text x="0" y="2" text-anchor="middle" font-size="5" fill="${C_TXT}" font-family="JetBrains Mono,monospace">${(child.name || child.spec).slice(0, 3).toUpperCase()}</text>\n',
    '              </g>\n',
    '            </g>\n',
    '          </g>\n',
    '        </g>\n',
    '      </g>`;\n',
    '    });\n',
    '  });\n',
    '\n',
    '  svg += \'</svg>\';\n',
    '  wrap.innerHTML = svg;\n',
    '\n',
    '  const dot = document.getElementById(\'cmd-live-dot\');\n',
    '  const txt = document.getElementById(\'cmd-live-txt\');\n',
    '  if(dot) dot.className = \'cmd-live-dot\'+(isThinking?\' thinking\':(btc?\'\':\' idle\'));\n',
    '  if(txt) {\n',
    '    txt.textContent = isThinking?\'THINKING — Sonnet 4.6 analyzing\':isDone?\'DECISION MADE\':(btc?\'MONITORING · live prices\':\'INITIALIZING\');\n',
    '    txt.style.color = isThinking?\'var(--cyan)\':isDone?\'var(--green)\':\'var(--text2)\';\n',
    '  }\n',
    '}\n'
]

lines[1944:2351] = new_func

with open(path, 'w') as f:
    f.writelines(lines)
